---
title: "DATA622_HW3"
author: "Robert Welk"
date: "9/24/2021"
output: html_document
---
chaqnge 1
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RCurl)
library(tidyverse)
library(DataExplorer)

df <- read.csv("https://raw.githubusercontent.com/robertwelk/DATA622/main/Loan_approval.csv") %>% as_tibble()


introduce(df)
```

Change data types 
```{r}
str(df)

df$Gender <- as.factor(df$Gender)
df$Married <- as.factor(df$Married)
df$Education <- as.factor(df$Education)
df$Self_Employed <- as.factor(df$Self_Employed)
df$Credit_History <- as.factor(df$Credit_History)
df$Property_Area <- as.factor(df$Property_Area)
df$Loan_Status <- as.factor(df$Loan_Status)

# new features
df$DEPENDENTS <- factor(ifelse(df$Dependents >=1, "YES", "NO")) # based on EDA
df <- df %>% dplyr::select(!Dependents)
```

Diagnostic Plots
Density
Boxplots
Correlation 
```{r}
plot_intro(df)
plot_missing(df)
plot_bar(df, by="Loan_Status")
plot_histogram(df)
plot_qq(df)

plot_correlation(na.omit(df), type="c")
plot_correlation(na.omit(df), type="d")
plot_boxplot(df, by="Loan_Status")


df %>% ggplot(aes(LoanAmount, col=Loan_Status)) + geom_density()
df %>% ggplot(aes(ApplicantIncome, col=Loan_Status)) + geom_density()
df %>% ggplot(aes(CoapplicantIncome, col=Loan_Status)) + geom_density()
df %>% ggplot(aes(Loan_Amount_Term, col=Loan_Status)) + geom_density()
```

PreProcessing
Handle Missing Values
Feature Engineering
  -   for example, dependents could be yes or no
One hot encoding for categorical

```{r}


```



LDA
```{r}

```

KNN
```{r}

```

Decision Tree
```{r}

```

Random Forest
```{r}

```

Compare Results
```{r}

```
